### ISSUE TITLE
Floating point numbers that end in .0 cannot be added to blocks

### ISSUE THREAD

**Issue by mybearworld** [gonfunko/scratch-blocks#157] opened 2024-09-01 21:20 UTC
### Expected Behavior

It should be possible to create a `pick random (1.0) to (10)` block. (This makes the block output a floating point number instead of an integer.)

**Screenshot from regular Scratch**
![pick random 1.0 to 10 block with 3.4339879999682923 as its output](https://github.com/user-attachments/assets/381f655d-22c3-4eda-af5d-60d606ae4472)

### Actual Behavior

Whenever you enter `1.` or `1.0` into a block, it autocorrects to "1".

### Steps to Reproduce

- Drag out any block that takes in a number.
- Try to enter "1.0".

### Operating System and Browser

Windows 11 on MS Edge 128

**Comment by GrahamSH-LLK** [comment] 2024-09-04 01:22
This is caused by the original scratch-blocks and modern Blockly implementations for decimals being very different- scratch-blocks has a custom rolled(?) regex implementation that simply checks for periods in the string. Blockly has a more robust approach that ends up stripping that "unneeded" decimal that VM relies on for the random behavior. I believe it happens [here](https://github.com/google/blockly/blob/0a6596ce75a0a29f05cedbe718fda84fb601b4f1/core/field_number.ts#L272)

Edit: this behavior was briefly fixed in https://github.com/gonfunko/scratch-blocks/pull/54 but was reverted

**Comment by rachel-fenichel** [comment] 2024-10-11 23:43
Thanks, both of you, for reporting this so cleanly and following with the _how_ of the bug as well as the _what_.  You're making our lives easier.

**Closed as completed** 2024-10-14 15:18 UTC

**Comment by plabanTest1** [comment] 2024-10-17 05:48
1.0 doesn't autocorrect to round number and stays as it is.

![image](https://github.com/user-attachments/assets/068ec39b-3f64-45ba-a96f-04bb8d870a8f)
