### ISSUE TITLE
Right click on a block has more options with respect to Scratch

### ISSUE THREAD

**Issue by plabanTest1** [gonfunko/scratch-blocks#173] opened 2024-09-09 10:29 UTC
- Load the URL
- Drag a random first block to work space
- Right click on the block

Currently the right click shows 5options(3 open options and 2 greyed out)

![Image](https://github.com/user-attachments/assets/9731b299-e4ac-469a-96ba-e920b7d8c060)

As per Scratch,

![Image](https://github.com/user-attachments/assets/a3ba4b4d-9d9d-49d5-8ee8-d36e54cb10ad)

**Comment by gonfunko** [comment] 2024-09-09 15:32
Duplicate of #174.

**Closed as completed by gonfunko** 2024-09-09 15:32 UTC
