### ISSUE TITLE
The text on the block when dragged to workspace and selected should not be bold.

### ISSUE THREAD

**Issue by plabanTest1** [gonfunko/scratch-blocks#104] opened 2024-08-05 11:13 UTC
1. Drag a block to the workspace that has textfield.
2. Select the text for edit (Double click on the text)

The text should not be bold as per Scratch.

![Image](https://github.com/user-attachments/assets/644137df-ff93-482c-a1aa-c2b6c6228124)

As per Scratch,

![Image](https://github.com/user-attachments/assets/cd9a7178-a233-4635-8049-3e2a7080da8e)

**Comment by gonfunko** [comment] 2024-08-05 18:03
Duplicate of #70

**Closed as completed by gonfunko** 2024-08-05 18:03 UTC

**Comment by plabanTest1** [comment] 2024-09-03 08:51
Working as expected.
![image](https://github.com/user-attachments/assets/aab4b8f2-d038-4df2-899b-af944af267a5)
