### ISSUE TITLE
The block drop destination highlights should use white instead of yellow.

### ISSUE THREAD

**Issue by plabanTest1** [gonfunko/scratch-blocks#108] opened 2024-08-06 05:21 UTC
1. Drag a block to the workspace
2. Drag another block into the previous block.

Currently the block drag to another block is highlighted using Yellow color. Scratch uses White color.

![Image](https://github.com/user-attachments/assets/94a4aef9-8829-41ec-8f76-73585284ed9f)

As per Scratch,

![Image](https://github.com/user-attachments/assets/4e68a60d-d876-437e-93a9-351ec6edf1ba)

**Comment by gonfunko** [comment] 2024-08-08 20:43
Duplicate of #71.

**Closed as completed by gonfunko** 2024-08-08 20:43 UTC

**Comment by plabanTest1** [comment] 2024-09-03 09:07
Working as expected now.


![Image](https://github.com/user-attachments/assets/180a970e-0a66-47cc-ae94-fa472c3e3c78)
