### ISSUE TITLE
Blocks in the flyout area is not appropriately separated.

### ISSUE THREAD

**Issue by plabanTest1** [gonfunko/scratch-blocks#97] opened 2024-08-05 06:09 UTC
The blocks in the flyout are not separated evenly as per Scratch

![Image](https://github.com/user-attachments/assets/744ead08-62ba-4a22-a530-745d1eb84f65)

**Comment by gonfunko** [comment] 2024-08-05 18:10
Duplicate of #69

**Closed as completed by gonfunko** 2024-08-05 18:10 UTC

**Comment by plabanTest1** [comment] 2024-08-29 17:19
Working as expected.



![Image](https://github.com/user-attachments/assets/6d834454-cd52-4c35-96c4-952078923f95)
