### ISSUE TITLE
The "Make a Block" and "Make a Variable" are not working under small screens like mobile/tablet

### ISSUE THREAD

**Issue by plabanTest1** [gonfunko/scratch-blocks#143] opened 2024-08-29 17:52 UTC
1. Navigate to the in-editor
2. Open the Developers tool.
3. Change the screen resolution to Mobile and tablet view. (375px & 768px)
4.  The new dialog box for block/variable creation is not displayed.

https://screencast.googleplex.com/cast/NjI5MzQ0MTY5NTcxMTIzMnxlZmRhNjRmZS01Yw

**Comment by gonfunko** [comment] 2024-09-17 22:04
Duplicate of #170.

**Closed as completed** 2024-09-17 22:06 UTC
