### ISSUE TITLE
The message "message1" is not yet selectable in the block pallete

### ISSUE THREAD

**Issue by mybearworld** [gonfunko/scratch-blocks#161] opened 2024-09-02 06:21 UTC
### Expected Behavior

When clicking the dropdown to select a message in the broadcast blocks, you can select "message1" and "New message".

**Screenshot from Scratch**
![image](https://github.com/user-attachments/assets/4d6d7880-2588-4b08-bcd8-00f2a26f3a39)

### Actual Behavior

You can only select "New message".

**Screenshot from this fork**
![image](https://github.com/user-attachments/assets/3950e200-f60c-4410-83dd-e949a677ed25)

Once you drag a broadcast block out, the problem goes away, even for the blocks in the pallet.

**Screenshot from this fork**
![image](https://github.com/user-attachments/assets/5cea3591-9c02-412d-a155-2e2ea9621a3e)

### Steps to Reproduce

- Go to the Events category
- Click on the dropdown on either `when I receive [message1 v]`, `broadcast [message1 v]` or `broadcast [message1 v] and wait` in the pallet
- Drag out one of the blocks above
- Click on the dropdown again

### Operating System and Browser

Windows 11 on MS Edge 128

**Comment by GrahamSH-LLK** [comment] 2024-09-02 18:05
Duplicate of #149

**Closed as not planned** 2024-09-02 18:17 UTC
