### ISSUE TITLE
On high contrast mode, the block drop destination highlights are not as per Scratch

### ISSUE THREAD

**Issue by plabanTest1** [gonfunko/scratch-blocks#177] opened 2024-09-10 09:26 UTC
- Set High contrast mode (Settings -> Color Mode)

![Image](https://github.com/user-attachments/assets/30826280-5b15-402f-b85e-587653b748c9)

As per Scratch,
![Image](https://github.com/user-attachments/assets/aabbfd96-9339-4e07-b336-e04e21206dd8)

**Comment by gonfunko** [comment] 2024-09-10 15:38
Duplicate of #156.

**Closed as completed by gonfunko** 2024-09-10 15:38 UTC

**Comment by plabanTest1** [comment] 2024-09-16 11:02
The block highlights are working as expected.

<img width="1792" alt="Screenshot 2024-09-16 at 4 31 23 PM" src="https://github.com/user-attachments/assets/29debefe-a135-475a-a96d-80a3c4762c76">
